- name: Update system packages
  ansible.builtin.apt:
    cache_valid_time: 3600
    upgrade: safe
    update_cache: true

- name: Create systemd resolved.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: "0755"

- name: Create systemd-resolved disable-stub-listener.conf
  ansible.builtin.copy:
    src: disable-stub-listener.conf
    dest: /etc/systemd/resolved.conf.d/disable-stub-listener.conf
    mode: "0644"
  notify:
    - Restart systemd-resolved.service

- name: Create resolve.conf symbolic link
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    mode: "0644"
    state: link
  notify:
    - Restart systemd-resolved.service
